spring:
  datasource:
    #url: jdbc:mysql://mysql:3306/microservices?serverTimezone=CET&createDatabaseIfNotExist=true
    url: jdbc:mysql://127.0.0.2:3306/shop?serverTimezone=CET&createDatabaseIfNotExist=true
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

